Distância até all - 0: all
Distância até all - 1: app
Distância até all - 1: tests
Distância até all - 2: core.o
Distância até all - 2: main.o
Distância até all - 2: test_run.o
Distância até all - 3: core.c
Distância até all - 3: core.h
Distância até all - 3: main.c
Distância até all - 3: test_run.c
