Distância até all - 0: all
Distância até all - 1: app
Distância até all - 1: lib
Distância até all - 1: utils
Distância até all - 2: l1.o
Distância até all - 2: l2.o
Distância até all - 2: main.o
Distância até all - 2: u1.o
Distância até all - 2: u2.o
Distância até all - 3: common.h
Distância até all - 3: l1.c
Distância até all - 3: l2.c
Distância até all - 3: main.c
Distância até all - 3: u1.c
Distância até all - 3: u2.c
Distância até all - 3: util.h
Distância até all - 4: base.h
Distância até all - 4: config.h
