Distância até all - 0: all
Distância até all - 1: core
Distância até all - 1: net
Distância até all - 1: tools
Distância até all - 1: ui
Distância até all - 2: m.o
Distância até all - 2: net.o
Distância até all - 2: pack.o
Distância até all - 2: ui.o
Distância até all - 2: util.o
Distância até all - 2: view.o
Distância até all - 3: common.h
Distância até all - 3: main.c
Distância até all - 3: net.c
Distância até all - 3: net.h
Distância até all - 3: pack.c
Distância até all - 3: pack.h
Distância até all - 3: ui.c
Distância até all - 3: ui.h
Distância até all - 3: util.c
Distância até all - 3: util.h
Distância até all - 3: view.c
Distância até all - 4: base.h
Distância até all - 4: gfx.h
Distância até all - 4: io.h
Distância até all - 4: math.h
Distância até all - 4: proto.h
