SEQ - 1: base.h
SEQ - 2: common.h
SEQ - 3: main.c
SEQ - 4: m.o
SEQ - 5: util.c
SEQ - 6: util.o
SEQ - 7: core
SEQ - 8: net.c
SEQ - 9: net.h
SEQ - 10: net.o
SEQ - 11: net
SEQ - 12: ui.h
SEQ - 13: view.c
SEQ - 14: view.o
SEQ - 15: ui
SEQ - 16: all
