DNA inteiro: TTAACAATTTGTGCTATTG
Trecho 12-15: GCT
DNA inteiro: TTAACAATTTGGTGCTATTG
DNA inteiro: TTAACAATTTGGGTGCTATTG
DNA inteiro: TTACAATTTGGGTGCTATTG
DNA inteiro: TTACAATTGGGTGCTATTG
DNA inteiro: TTACAATTGGGTAGCTATTG
DNA inteiro: TTCACAATTGGGTAGCTATTG
DNA inteiro: TTCACAATTGGGGTAGCTATTG
DNA inteiro: TTCACAATTGGGGTAAGCTATTG
Trecho 10-17: GGGTAAG
DNA inteiro: TTCACAATTTGGGGTAAGCTATTG
DNA inteiro: TTACAATTTGGGGTAAGCTATTG
Contagem final: A:6 T:9 C:2 G:6
